openapi: '3.0.3'

info:
    title: Facebook
    version: 1.0.0
    description: Facebook API

servers:
  - url: http://localhost:9000/api
    description: Local Server

paths:
    /api/posts/create:
        post:
            tags:
                - Post
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/PostCreateRequest'

            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/PostResponse'

components:
    schemas:
        PostCreateRequest:
            type: object
            required:
                - userId
                - description
            properties:
                userId:
                    type: integer
                    format: int64
                description:
                    type: string
                imgUrl:
                    type: string
                    nullable: true

        PostResponse:
            type: object
            properties:
                user:
                    $ref: '#/components/schemas/UserPostDTO'
                description:
                    type: string
                imgUrl:
                    type: string
                created:
                    type: string
                    format: date-time

        UserPostDTO:
            type: object
            properties:
                id:
                    type: integer
                    format: int64
                firstName:
                    type: string
                lastName:
                    type: string
