server:
  port: 9000

spring:
  application:
    name: facebook

  config:
    import: optional:file:.env[.properties]

  profiles:
    active: local # Or prod based on your environment

  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_SENDER_USERNAME}
    password: ${EMAIL_SENDER_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

springdoc:
  swagger-ui:
    path: /docs/api.html

logging:
  level:
    org.springframework.security: debug

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

# Configuration for the local profile
---
spring.config.activate.on-profile: local

app:
  frontend:
    url: http://localhost:5173
spring:
  datasource:
    url: jdbc:h2:mem:facebook;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  h2:
    console:
      enabled: true

  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: always

  # Flyway settings
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    enabled: false # H2 2.3.232 is newer than this version of Flyway and support has not been tested. The latest supported version of H2 is 2.2.224.#

  mail:
    properties:
      mail.smtp.ssl.trust: "*"
      mail.smtp.ssl.checkserveridentity: false

# Configuration for the prod profile
---
spring.config.activate.on-profile: prod

app:
  frontend:
    url: https://final-project-frontend-c220f8.gitlab.io

spring:
  datasource:
    url: jdbc:mysql://mysql-java-hsachok-test1.g.aivencloud.com:27453/facebook?sessionVariables=sql_require_primary_key=OFF
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: avnadmin
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  # Flyway settings
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    enabled: true