server:
  port: 9000

spring:
  application:
    name: facebook

  profiles:
    active: local # Or prod based on your environment

logging:
  level:
    org.springframework.security: debug

# Configuration for the local profile
---
spring.config.activate.on-profile: local

spring:
  datasource:
    url: jdbc:h2:mem:facebook
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  h2:
    console:
      enabled: true

  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

  # Flyway settings
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    enabled: false # H2 2.3.232 is newer than this version of Flyway and support has not been tested. The latest supported version of H2 is 2.2.224.#

# Configuration for the prod profile
---
spring.config.activate.on-profile: prod

spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:mysql://mysql-java-hsachok-test1.g.aivencloud.com:27453/facebook?sessionVariables=sql_require_primary_key=OFF
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: avnadmin
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  # Flyway settings
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    enabled: true